package Frames;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONObject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author straf
 */
public class NPCScreen extends javax.swing.JInternalFrame {

    
    
    public NPCScreen() {

        
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genNPC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        NPCviewer = new javax.swing.JEditorPane();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        genNPC.setText("Generate");
        genNPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                genNPCMouseReleased(evt);
            }
        });
        genNPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genNPCActionPerformed(evt);
            }
        });
        genNPC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                genNPCKeyReleased(evt);
            }
        });

        jScrollPane1.setViewportView(NPCviewer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(genNPC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(genNPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genNPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genNPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genNPCActionPerformed

    private void genNPCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genNPCKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_genNPCKeyReleased

    private void genNPCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genNPCMouseReleased
        
        try {
            System.out.println("Making Guy!");
            
            JSONObject tmpNPC = NPCGenerator.generateNPC();
            
            
            NPCviewer.setText(NPCGenerator.display(tmpNPC));
        } catch (IOException ex) {
            Logger.getLogger(NPCScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_genNPCMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane NPCviewer;
    private javax.swing.JButton genNPC;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
    

